export const OrderItem = [
  {
    "id": 1,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  },
  {
    "id": 2,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  },
  {
    "id": 3,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  },
  {
    "id": 4,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  },
  {
    "id": 5,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  },
  {
    "id": 6,
    "productCode": "SP1",
    "productName": "SP1 Name",
    "productOrderId": 8,
    "bomVersion": "1.1",
    "note": "note",
    "status": "chờ sản xuất",
    "startDate": "3/8/2023",
    "endDate": "1/9/2023",
    "quantity": 100,
    "quantityOut": 100
  }]